### PR TITLE
rename_affine_2nd_try

### PR DESCRIPTION
**Pull request by vivanraaj**
2nd try for pull request to rename affine as per issue #692 title

### CODE REVIEW

**Comment by mimoo** [comment]
looks like a number of tests don't pass, try to run `cargo test` locally and make sure everything works :o

**Comment by vivanraaj** [comment]
some issues with earlier pull request:
- I had to install ocaml in ubuntu system. The instructions did not specify this step.
- There was issue with the renaming symbol function in VS Code. It somehow renamed the called function again in other code file that were generating error.

**Comment by mimoo** [comment]
> I had to install ocaml in ubuntu system. The instructions did not specify this step.

if you want to create a PR to add this step in the `CONTRIBUTING.md` or somewhere relevant I'll accept it!

> There was issue with the renaming symbol function in VS Code. It somehow renamed the called function again in other code file that were generating error.

Ah, interesting. I guess I always suspected that this function couldn't work perfectly in all cases :D

**Comment by vivanraaj** [comment]
> > I had to install ocaml in ubuntu system. The instructions did not specify this step.
> 
> if you want to create a PR to add this step in the `CONTRIBUTING.md` or somewhere relevant I'll accept it!
No, its my bad. This step was written in the `CONTRIBUTING.md`. I missed it.

> > There was issue with the renaming symbol function in VS Code. It somehow renamed the called function again in other code file that were generating error.
> 
> Ah, interesting. I guess I always suspected that this function couldn't work perfectly in all cases :D
Yes, i assume its related to the rust analyzer extension.

**Comment by vivanraaj** [comment]
> > > I had to install ocaml in ubuntu system. The instructions did not specify this step.
> > 
> > 
> > if you want to create a PR to add this step in the `CONTRIBUTING.md` or somewhere relevant I'll accept it!
> > **No, its my bad. This step was written in the `CONTRIBUTING.md`. I missed it.**
> 
> > > There was issue with the renaming symbol function in VS Code. It somehow renamed the called function again in other code file that were generating error.
> > 
> > 
> > Ah, interesting. I guess I always suspected that this function couldn't work perfectly in all cases :D
> > **Yes, i assume its related to the rust analyzer extension.**

**Comment by mimoo** [comment]
looks like you meant to say something? But I don't see any of your text.

Also a good idea, instead of creating many PRs, would be to just force push your new changes on this branch

**Pull request closed without merging**
