### PR TITLE
[easy] remove dead code

### PR DESCRIPTION
**Pull request by mimoo**
it seems like we were using these functions (ToBytes, FromBytes) and traits (num-derive) before we moved to serde for serialization. So removing this code now.

### CODE REVIEW

**Comment by mrmr1993** [comment]
Can you make a corresponding mina PR, to confirm that this code is dead?

**Comment by mimoo** [comment]
will do after I can get the double generic gate in

**Review by jspada — COMMENTED** [review]
Assuming it's not used from `mina`, then good to remove.

**Comment by joseandro** [comment]
@mimoo what's the latest on this?

**Comment by mimoo** [comment]
keeping it around until I have time to do it. BTW we already have a bot checking on stale PRs/issues ;)

**Pull request closed without merging**
