### PR TITLE
Unit test for `StoreWordLeft`

### PR DESCRIPTION
**Pull request by querolita**
Fixes the interpreter to behave like Cannon.

### CODE REVIEW

**Comment by dannywillems** [comment]
If the instruction wasn't implemented incorrectly, it means we never had it in the past. I'm running the o1VM on the real infra to check this assumption.

**Comment by dannywillems** [comment]
Without checking your changes, I think the previous implementation is correct. Running on your branch gives me this exit code:
```
Exited with code 2 at step 298805823
Halted at step=15726623 instruction=RType(SyscallExitGroup)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConstraintNotSatisfied("Unsatisfied expression: ((((Curr(x[16]) - 0x0100000000000000000000000000000000000000000000000000000000000000) * Curr(x[25])) + Curr(x[24])) - 0x0100000000000000000000000000000000000000000000000000000000000000)")', o1vm/src/main.rs:235:46
```

**Comment by querolita** [comment]
@dannywillems 

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConstraintNotSatisfied("Unsatisfied expression: ((((Curr(x[16]) - 0x0100000000000000000000000000000000000000000000000000000000000000) * Curr(x[25])) + Curr(x[24])) - 0x0100000000000000000000000000000000000000000000000000000000000000)")', o1vm/src/main.rs:235:46

This used to fail before as well, as tracked here -> https://github.com/o1-labs/proof-systems/issues/2075

**Comment by querolita** [comment]
Demo halts, making the PR a draft until solved

**Comment by querolita** [comment]
Closing due to https://github.com/o1-labs/proof-systems/pull/2729/

**Pull request closed without merging**
