### PR TITLE
add license to all Cargo.toml

### PR DESCRIPTION
**Pull request by hanabi1224**
Supplement https://github.com/o1-labs/proof-systems/pull/234 and add license field to all Cargo.toml files.

### CODE REVIEW

**Review by mimoo — APPROVED** [review]
thanks!

**Comment by hanabi1224** [comment]
Hey @mimoo  looks like ci get stuck for some reason, can you please help re-run it?

**Comment by mimoo** [comment]
not sure why it was stuck, let's see if this works

**Comment by hanabi1224** [comment]
Thanks!

**Pull request merged**
