### PR TITLE
renaming affine try#3

### PR DESCRIPTION
**Pull request by vivanraaj**
renamed affine as per issue title #692 .

### CODE REVIEW

**Comment by vivanraaj** [comment]
thats weird. i already made the changes but somehow it is still showing the unchanged codes.

**Comment by mimoo** [comment]
looks like `cargo test` doesn't return clean

**Comment by vivanraaj** [comment]
can you try again? i pushed another commit on this same branch which should pass "Cargo test"

**Review by mimoo — APPROVED** [review]
Nice! Thanks a lot for your first contribution :)

**Pull request merged**
