### PR TITLE
Unit test for `LoadWordRight`

### PR DESCRIPTION
**Pull request by querolita**
Fixes interpreter to behave like Cannon.

### CODE REVIEW

**Comment by querolita** [comment]
I am running locally the `lwl` test with the failing seed `[238, 109, 123, 126, 100, 197, 79, 65, 213, 118, 69, 185, 50, 130, 195, 73, 179, 75, 23, 168, 45, 145, 206, 140, 231, 237, 38, 127, 252, 224, 52, 38]` and I am getting a subtract overflow inside the `access_register_if`. I believe this is due to this fixme `FIXME: A register should allow multiple accesses within the same instruction.`, because it tries to subtract to the instruction counter the last accessed time which was set to be `instruction_counter +1` in the previous call to `access_register_if`. In particular, `LoadWordLeft` performs at least three register accesses per call, so that "time travelling" technique is not enough in this case.

**Comment by dannywillems** [comment]
As for swl, I'm getting an error:

```

[2024-06-13T14:55:13Z INFO  o1vm::mips::witness] processing step=0 pc=00000ae88c insn=000802ba1f ips=0.00 pages=8598 mem=33.6 MiB name=_rt0_mips_linux
[2024-06-13T14:55:17Z INFO  o1vm::mips::witness] Snapshot state in snapshot-state-0.json, step 0
Exited with code 2 at step 92444315
Halted at step=4865491 instruction=RType(SyscallExitGroup)
```

**Comment by dannywillems** [comment]
On input:
```
export L1_HEAD=0x05331e9873c201c108c1321d2488b298e8c1debe0429a054f7b0227e57821701
export L2_HEAD=0x81a28a79d8d687b048962799e98f2c5bc907b8bcd54c2ad948be9ca3fc4328f3
export L2_BLOCK_NUMBER=11729810
export STARTING_OUTPUT_ROOT=0x6487e31240348b7e3b7ea873e7acedfd406fd0538039cd9c75e3c2a5f42d49d1
export L2_CLAIM=0x358f7d8ace011fb2d773f2e85a55fffd4c37a55e733475990f1c896fbe7c93c7
```

**Review by dannywillems — CHANGES_REQUESTED** [review]
Because of the failing e2e test

**Comment by querolita** [comment]
Demo halts, making the PR a draft until solved

**Comment by querolita** [comment]
Closing due to https://github.com/o1-labs/proof-systems/pull/2729/

**Pull request closed without merging**
