### PR TITLE
MVPoly: implement random

### PR DESCRIPTION
**Pull request by dannywillems**

### CODE REVIEW

**Review by Fizzixnerd — COMMENTED** [review]
I feel like having `random` be part of the public interface is a little dangerous, as it may provide guarantees about randomness that you didn't mean to.

**Comment by dannywillems** [comment]
> about randomness that you didn't mean to.

What do you mean?

We often provide a rand/random methods to generate values for testing, in particular. I do not plan to use it, but for testing. I can move (in a follow-up PR) the method into the tests directory, if you don't want to have it in the public interface. I'm fine with this.

**Comment by Fizzixnerd** [comment]
> > about randomness that you didn't mean to.
> 
> What do you mean?
> 
> We often provide a rand/random methods to generate values for testing, in particular. I do not plan to use it, but for testing. I can move (in a follow-up PR) the method into the tests directory, if you don't want to have it in the public interface. I'm fine with this.

I was worried that someone might use these in a probabilistic protocol as a source of randomness, which is presumably not what you wanted.  If people aren't going to be writing code like that, I'm happy to approve.

**Review by Fizzixnerd — APPROVED** [review]

**Comment by dannywillems** [comment]
> > > > about randomness that you didn't mean to.
> > > 
> > > 
> > > What do you mean?
> > > We often provide a rand/random methods to generate values for testing, in particular. I do not plan to use it, but for testing. I can move (in a follow-up PR) the method into the tests directory, if you don't want to have it in the public interface. I'm fine with this.
> > 
> > 
> > I was worried that someone might use these in a probabilistic protocol as a source of randomness, which is presumably not what you wanted. If people aren't going to be writing code like that, I'm happy to approve.
> 
> I see. Worth using `unsafe` then. Doing in a follow-up.

See https://github.com/o1-labs/proof-systems/pull/2498

**Pull request merged**
