### PR TITLE
[develop] Use seedable rng for some tests

### PR DESCRIPTION
**Pull request by dannywillems**
Part of https://github.com/MinaProtocol/mina/issues/14664

### CODE REVIEW

**Review by rbonichon — APPROVED** [review]
How do we pass the seed to replay a failing test?

**Review by querolita — APPROVED** [review]
Let's hope this helps with narrowing down the randomly failing test!

**Comment by querolita** [comment]
> How do we pass the seed to replay a failing test?

Manual inspection after CI obtains a failing test I guess. My understanding is that this is mostly for debugging purposes.

**Comment by dannywillems** [comment]
> How do we pass the seed to replay a failing test?

Mmh, at the moment, as a first step, I was thinking about simply copy/paste it.

**Comment by dannywillems** [comment]
> > How do we pass the seed to replay a failing test?
> 
> Mmh, at the moment, as a first step, I was thinking about simply copy/paste it.

I would like to see it adopted by all tests, or something of this kind in the rest of the repository. We can use this PR or the issue to discuss the API.

**Pull request merged**
