### PR TITLE
Purge gate folder

### PR DESCRIPTION
**Pull request by frisitano**
This PR migrates code from `kimchi/src/circuits/gates/` to the corresponding file in `kimichi/src/circuits/polynomials/`.  The empty `kimchi/src/circuits/gates/` folder has then been purged. 

closes: #202

### CODE REVIEW

**Comment by frisitano** [comment]
Please do not merge just yet.  After reading https://www.cryptologie.net/article/553/the-code-is-the-specification-introducing-cargo-spec/ I want to investigate if any of the changes I have made have broken the spec and if so I will fix.

**Comment by frisitano** [comment]
just checked and it doesn't look like this will impact the spec.

**Comment by mimoo** [comment]
CI would actually have yelled at you if you changed something in the spec :) so don't worry. Thanks a lot for this PR!

**Comment by mimoo** [comment]
sorry, one more thing. In other polynomials we've always had the gate construction code first, and then the constraints after, but in your PR you added the gate stuff at the end of the file instead of at the beginning. Would you mind changing that and moving things to the beginning of the file instead? Just so that we're consistent.

**Pull request merged**
