### PR TITLE
snarky EC

### PR DESCRIPTION
**Pull request by fabrizio-m**

### CODE REVIEW

**Comment by mimoo** [comment]
Ouch, that's actually really verbose. The more I'm thinking about that, the more I'm thinking that semantically it doesn't make sense either does it? A circuit is something that's written over a field, not over a curve. I think it's fine to have the KimchiCurve be passed in the `new()` function of RunState, and we can take the constants and all we want from there then (which is what we do already no?), but passing the curve everywhere seems counter productive no?

**Comment by fabrizio-m** [comment]
I was thinking about that, and I also noticed that even if I make the snarky gates generic, the kimchi gates are not generic and only work with pasta or curves with a very similar law.
My main interest to access the curve is to avoid reimplementing it inside `compute()`, what about this:
```rust
pub trait SnarkyField: PrimeField {
    type Curve: AffineCurve<BaseField = Self>;
}
``` 
We replace `PrimeField` with a subtrait that offers access to the curve, the code will the be same as before.

**Comment by mimoo** [comment]
> My main interest to access the curve is to avoid reimplementing it inside compute(), what about this:

Can't you just use the closure to capture the values (which are IIUC the round constants)?

**Comment by fabrizio-m** [comment]
Round constants are in poseidon, here I need the implementation of elliptic curve operations that live in `AffineCurve` and `GroupAffine`, I'll soon add a commit with an example of it would work with the trait.

**Comment by mimoo** [comment]
is it to verify that the operations are correctly done? Just looking at izaak's circuit-construction he doesn't use the group operations, at least for the ec_add gate (https://github.com/o1-labs/proof-systems/blob/mimoo%2Fsnarky/circuit-construction/src/writer.rs#L263)

**Comment by fabrizio-m** [comment]
The kimchi gate basically takes 3 points and some other info and enforces that the third is the sum of the first 2 but starting from two points I have to compute the third and the other things.
Izaak is reimplementing the group operation in that function, I can do the same, it just seems to me more maintainable to reuse ark-ec.

**Comment by fabrizio-m** [comment]
It seems that I will have to reimplement some parts anyway to access some of the intermediate values, so I can just implement the whole operation.

**Comment by mimoo** [comment]
btw something else we can do in Rust, if this is something we think we need down the line, is to preserve the `KimchiCurve` we pass in `new()` in the runstate (we can do that using `PhantomData`)

**Pull request closed without merging**
