### PR TITLE
Add missing register constants v0 and v1

### PR DESCRIPTION
**Pull request by dannywillems**

### CODE REVIEW

**Review by querolita — APPROVED** [review]

**Review by querolita — COMMENTED** [review]
Looks like this PR is in conflict with this one https://github.com/o1-labs/proof-systems/pull/1450

**Review by mrmr1993 — CHANGES_REQUESTED** [review]
Please delete all of the names, a la https://github.com/o1-labs/proof-systems/pull/1450

**Comment by mrmr1993** [comment]
@dannywillems can we close this?

**Comment by dannywillems** [comment]
Yes, closing.

**Pull request closed without merging**
