### PR TITLE
MVPoly: implement mul_by_const for prime::Dense

### PR DESCRIPTION
**Pull request by dannywillems**

### CODE REVIEW

**Review by Fizzixnerd — APPROVED** [review]
NitPick (NP): Possibly a better name would be `scalar_mul` or `mul_by_scalar`, as you are using the word `const` here to mean "constant polynomial", but then you pass in a field element, i.e. not a polynomial (but obviously could represent one).  Up to you, I leave to your judgement.

**Comment by dannywillems** [comment]
Agree with mul_by_scalar. Changing.

**Comment by dannywillems** [comment]
> NitPick (NP): Possibly a better name would be `scalar_mul` or `mul_by_scalar`, as you are using the word `const` here to mean "constant polynomial", but then you pass in a field element, i.e. not a polynomial (but obviously could represent one). Up to you, I leave to your judgement.

See https://github.com/o1-labs/proof-systems/pull/2497

**Review by Fizzixnerd — APPROVED** [review]
approving as part of train.

**Pull request merged**
