### PR TITLE
Fix sudoku test

### PR DESCRIPTION
**Pull request by katat**
Here tries to support both "and" "or" gates to the circuit API. 

As you can see, they accompany the unit tests, which I try to keep the coupling of tests minimal while maximizing the coverage by explicitly expressing the expectations for each new implementation. 

As always, please feel free to comment :)

### CODE REVIEW

**Comment by mimoo** [comment]
I think there was a merge issue or something :o ?

**Comment by katat** [comment]
My branch has merged with the current master branch, so it seems to be a lot of commits as well as conflicts in this PR.

Maybe your branch could have a sync with the master branch or get merged into it, then I re-create this PR? Happy to help to get this sudoku example merged into master branch :)

**Comment by mimoo** [comment]
rebased

**Comment by mimoo** [comment]
still looks weird no o.o ?

**Pull request closed without merging**
