### PR TITLE
`Fr_Sponge::absorb_evaluations` should have deconstructed `ProofEvaluations`

### PR DESCRIPTION
**Pull request by duguorong009**
Reference: #841

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]
Perfect! It might be good to do the same for [`lookup`](https://github.com/o1-labs/proof-systems/pull/875/files#diff-9fa21c48e781e815e967e2368ee4d75d90f9907650a8055a6e1cd0272289a1b0R114) too (but feel free to do it in a separate PR).

Thanks!

**Comment by duguorong009** [comment]
> Perfect! It might be good to do the same for [`lookup`](https://github.com/o1-labs/proof-systems/pull/875/files#diff-9fa21c48e781e815e967e2368ee4d75d90f9907650a8055a6e1cd0272289a1b0R114) too (but feel free to do it in a separate PR).
> 
> Thanks!

Yes, it is a good idea.(I missed)
I will add commit of `lookup deconstruction` to this PR.

**Comment by duguorong009** [comment]
@mrmr1993 
Can you please re-check the commit?
(Running unit tests takes so MUCH time ⏲️ )

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
> Running unit tests takes so MUCH time

A lot of the tests are really slow with the standard build profile. The tests still take a while, but should be faster if you run `cargo test --release` (or equivalent), if you haven't been already!

**Comment by duguorong009** [comment]
> > Running unit tests takes so MUCH time
> 
> A lot of the tests are really slow with the standard build profile. The tests still take a while, but should be faster if you run `cargo test --release` (or equivalent), if you haven't been already!

Thanks! It really works. 🚀 
Will push the commit of fmt + clippy.

**Comment by duguorong009** [comment]
@mrmr1993 
Now, the PR passes the CI.
Thanks for the support & tips!

**Pull request merged**
