### PR TITLE
[berkeley] Update curves to arkworks 0.4.2

### PR DESCRIPTION
**Pull request by mrmr1993**
This is https://github.com/o1-labs/proof-systems/pull/1669 merged into the berkeley branch

### CODE REVIEW

**Comment by mrmr1993** [comment]
Running tests on the Mina branch [here](https://github.com/MinaProtocol/mina/tree/feature/update_curves_to_arkworks_042-compatible), this seems to make proving 2x slower. We should *not* merge this.

**Comment by volhovm** [comment]
For my notes: `cargo test --package kimchi --lib -- tests::serde::tests::test_srs_serialization --exact --nocapture` fails for me on this branch.

**Comment by volhovm** [comment]
Upd: serialization solved in https://github.com/o1-labs/proof-systems/pull/2474 + added a test.

**Comment by volhovm** [comment]
Closed in favour of:
- https://github.com/o1-labs/proof-systems/pull/2474
- https://github.com/o1-labs/proof-systems/pull/2588

**Pull request closed without merging**
