### PR TITLE
Adding GPU-accelerated MSM implementation

### PR DESCRIPTION
**Pull request by mimoo**
This PR adds a GPU-accelerated implementation for MSM: https://github.com/supranational/pasta-msm/blob/main/Cargo.toml

Mina side: https://github.com/MinaProtocol/mina/pull/12602)

## Stability?

I did run into some weird mutex bug that I can't reproduce anymore (https://github.com/supranational/pasta-msm/issues/2) so I'm putting this behind a `gpu` feature.

## Setup

You need a [CUDA-compatible GPU](https://developer.nvidia.com/cuda-gpus) for this to work. If you don't, it'll try to fall back on an AVX CPU implementation which seems to be somewhat faster than arkworks in my case.

You also need to have `nvcc` in your path. On Ubuntu I had to downgrade to g++-10 and c++-10 to make it work (make sure that `cc`, `c++`, also point to `gcc-10` and `g++-10` using `update-alternatives`)

## Run the bench

The bench can be ran with:

```
$ cargo criterion -p o1-utils --bench msm --features gpu
```

it only runs on small URS size. It's expected that the GPU implementation only starts getting interesting around MSM of size 128.

There's a simple test that measures a larger URS (2^18) can be run by doing:

```
$ cargo test --release --package o1-utils --features gpu -- --ignored large_msm --nocapture
```

## ADX implementation

The test running without the GPU impl but the ADX impl shows a 10ms difference for me:

```
$ cargo test --release --package o1-utils --features gpu -- --ignored large_msm --nocapture
running MSM of size 262144
cpu msm took: 281.071544ms
gpu msm took: 271.999473ms
```

if I do 100 of them the gap increases, so perhaps this is good

```
running MSM of size 262144
100 cpu msm took: 43.320211253s
100 gpu msm took: 35.781777069s
```

## Sanity of integration

Here's a flamegraph, from my reading our usage is not spending much time doing non-useful things (like converting types).

flamegraph

## GPU numbers

I'm getting really bad numbers for the GPU implementation. It's basically almost 5x slower than the non-GPU implementation. My guess is that it's because I'm running things in WSL and I misconfigured something.

It'd be good to have someone running linux with a CUDA-compatible GPU to perform some bench here : o

### CODE REVIEW

**Comment by duguorong009** [comment]
@mimoo 
I found the request on the twitter.(https://twitter.com/cryptodavidw/status/1621948382683213824).
Here is one result I could provide.
```


Gnuplot not found, using plotters backend
arkworks msm of length 20                                                                            
                        time:   [194.16 µs 209.35 µs 226.38 µs]

Benchmarking supra msm of length 20: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.0s, enable flat sampling, or reduce sample count to 70.
supra msm of length 20  time:   [994.78 µs 994.90 µs 995.04 µs]                                    

arkworks msm of length 128                                                                            
                        time:   [292.83 µs 298.58 µs 304.91 µs]

supra msm of length 128 time:   [327.28 µs 350.70 µs 374.59 µs]                                    

arkworks msm of length 200                                                                            
                        time:   [394.92 µs 401.60 µs 409.36 µs]

supra msm of length 200 time:   [531.23 µs 574.51 µs 620.00 µs]                                    

arkworks msm of length 400                                                                            
                        time:   [658.72 µs 686.92 µs 719.91 µs]

Benchmarking supra msm of length 400: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.7s, enable flat sampling, or reduce sample count to 60.
supra msm of length 400 time:   [1.0556 ms 1.0877 ms 1.1170 ms]                                     
```

Here is the GPU info.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   51C    P8    16W /  N/A |     54MiB /  8192MiB |     19%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2415      G   /usr/lib/xorg/Xorg                 53MiB |
+-----------------------------------------------------------------------------+
```

**Comment by mimoo** [comment]
thanks @duguorong009 , looks like your GPU was truncated but I see cuda so most likely cuda compatible :o indeed these don't seem like great benchmarks as well. I'm wondering what's going on there...

**Comment by mimoo** [comment]
Note to myself: the implementation actually falls back to ADX (non-GPU) for MSM of size < 2^16

**Review by fabrizio-m — COMMENTED** [review]
aside from todos looks good to me.

**Pull request closed without merging**
